apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: devops-assessment
type: Opaque
stringData:
  DATABASE_URL: postgresql://devops:devops123@postgres:5432/devopsdb
  REDIS_URL: redis://redis:6379
