apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-assessment
data:
  log_level: "info"
  environment: "development"
  database_url: "postgresql://devops:devops123@postgres:5432/devopsdb"
  redis_url: "redis://redis:6379"
