apiVersion: v2
name: devops-assessment
description: A Helm chart for the DevOps assessment application including PostgreSQL and Redis
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: jardahrazdera
    email: jarek@jaroslav.tech
