apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-assessment.fullname" . }}-config
  labels:
    {{- include "devops-assessment.labels" . | nindent 4 }}
data:
  log_level: {{ .Values.config.logLevel | quote }}
  environment: {{ .Values.config.environment | quote }}
