{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-assessment.fullname" . }}-postgres
  labels:
    {{- include "devops-assessment.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    {{- include "devops-assessment.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
